import Navbar from './navbar'

export default function Header ({title}) {
    return (
        <>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <Navbar />
        </>
    )
}